name: flutter_app
description: Template project for flutter apps.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+10000000 #1 00 00 000


environment:
  # TODO: Hold the version back to 3.6.0, until the formatting is fixed(https://github.com/dart-lang/dart_style/issues/1253)
  sdk: ">=3.6.0 <4.0.0"
  flutter: 3.29.0


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

  # Navigation
  auto_route: 9.3.0+1

  # Data Structures
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

  # Network
  dio: 5.8.0+1

  # Storage
  shared_preferences: 2.5.2

  # Firebase
  firebase_analytics: 11.4.2
  firebase_auth: 5.4.2
  firebase_core: 3.11.0
  firebase_crashlytics: 4.3.2
  firebase_dynamic_links: 6.1.2
  firebase_messaging: 15.2.2
  firebase_remote_config: 5.4.0

  # Authentication
  google_sign_in: 6.2.2
  sign_in_with_apple: 6.1.4

  # Device
  device_info_plus: 11.3.0
  package_info_plus: 8.2.1
  path_provider: 2.1.5
  window_manager: 0.4.3

  # Security
  freerasp: 6.11.0

  # Logging
  pretty_dio_logger: 1.4.0
  talker: 4.4.7
  talker_flutter: 4.4.7
  talker_dio_logger: 4.4.7

  # Resources
  extended_image: 9.1.0
  flutter_native_splash: 2.4.5
  flutter_svg: 2.0.17
  intl: 0.19.0

  # UI
  flutter_animate: 4.5.2
  flutter_local_notifications: 18.0.1
  modal_bottom_sheet: 3.0.0
  universal_html: 2.2.4

  # Utility
  app_settings: 5.2.0
  collection: 1.19.1
  crypto: 3.0.6
  url_launcher: 6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build Runner
  build_runner: 2.4.15

  # State management
  riverpod_generator: 2.6.4

  # Navigation
  auto_route_generator: 9.3.1

  # Data Structures
  freezed: 2.5.8
  json_serializable: 6.9.4

  # Resources
  flutter_gen_runner: 5.9.0

  # Lint
  custom_lint: 0.7.3
  flutter_lints: 5.0.0
  riverpod_lint: 2.6.4

  # UI Tests
  patrol: 3.14.0


patrol:
  app_name: flutter_app
  android:
    package_name: com.strv.flutter.template
  ios:
    bundle_id: com.strv.flutter.template


flutter_gen:
  output: lib/assets/

  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay.ttf
