name: "[CodeCheck] Flutter - Android"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codestyle-check-android:
    name: Project CodeCheck

    runs-on: ubuntu-latest
    # runs-on: [self-hosted, macOS, flutter-builds]  # use this for self-hosted runners
    timeout-minutes: 15

    steps:
      - name: "[Setup - Checkout]"
        uses: actions/checkout@v4.2.2

      - name: "[Setup - Java]"
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle

      - name: "[Setup - Flutter Actions with Cache]"
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true
          architecture: x64
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      # Make gen
      - name: "[Flutter - Generate code]"
        run: make runner_gen

      # Run linter
      - name: "[Flutter - Run Linter]"
        run: flutter analyze

      # Build is slightly faster when targeting single platform, debug version and only apk instead of appbundle
      - name: "[Flutter - Build APK]"
        run: flutter build apk -t lib/main_develop.dart --flavor develop --target-platform android-arm64 --debug

      # Only on self hosted. Cleanup the files after the build
      # - name: '[Finish - Cleanup]'
      #   run: |
      #     rm -rf ./* || true
      #     rm -rf ./.??* || true
